name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  release:
    types: [published]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Print the tag name
        run: |
          echo ${{ github.ref }}

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "This job's status is ${{ job.status }}."
      - run: mvn clean install

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Upload file 1
        run: |
          gh release upload ${{github.event.release.tag_name}} agent/service/target/MFT-Agent-0.01-bin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload file 2
        run: |
          gh release upload ${{github.event.release.tag_name}} standalone-service/target/Standalone-Service-0.01-bin.zip      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release to get an id
      #   id: create_release_id
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}

      # - name: Upload Zip File 1
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release_id.outputs.upload_url }}
      #     asset_path: agent/service/target/MFT-Agent-0.01-bin.zip
      #     asset_name: MFT-Agent-0.01-bin.zip
      #     asset_content_type: application/zip

      # - name: Upload Zip File 2
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release_id.outputs.upload_url }}
      #     asset_path: standalone-service/target/Standalone-Service-0.01-bin.zip
      #     asset_name: Standalone-Service-0.01-bin.zip
      #     asset_content_type: application/zip
